/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import com.mysql.jdbc.Connection;
import java.awt.Cursor;
import java.awt.Toolkit;
import java.io.File;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

/**
 *
 * @author Naveen
 */
public class insert extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
   
    public insert() {
        initComponents();
        setLocation(250,100);
        setResizable(false);
        setIcon();
        setTitle("2 Pics 1 Word");
        max_sno();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        snoTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nolTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ansTF = new javax.swing.JTextField();
        q1 = new javax.swing.JLabel();
        ques_but1 = new javax.swing.JTextField();
        ques_but2 = new javax.swing.JTextField();
        ques_but3 = new javax.swing.JTextField();
        ques_but4 = new javax.swing.JTextField();
        ques_but5 = new javax.swing.JTextField();
        ques_but6 = new javax.swing.JTextField();
        ques_but7 = new javax.swing.JTextField();
        ques_but8 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        ans_but1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        q2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        insertButton = new javax.swing.JLabel();
        ans_but2 = new javax.swing.JTextField();
        ans_but3 = new javax.swing.JTextField();
        ans_but4 = new javax.swing.JTextField();
        ans_but5 = new javax.swing.JTextField();
        ans_but6 = new javax.swing.JTextField();
        ans_but7 = new javax.swing.JTextField();
        ans_but8 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usericon = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_icon.png"))); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(410, 0, 100, 110);

        snoTF.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        snoTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                snoTFFocusLost(evt);
            }
        });
        snoTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snoTFActionPerformed(evt);
            }
        });
        jPanel2.add(snoTF);
        snoTF.setBounds(490, 110, 90, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("No. of Letter");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(310, 180, 170, 20);

        nolTF.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        nolTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nolTFActionPerformed(evt);
            }
        });
        jPanel2.add(nolTF);
        nolTF.setBounds(490, 180, 90, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("S.No");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(360, 110, 70, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Answer");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(350, 250, 110, 20);

        ansTF.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        ansTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ansTFFocusLost(evt);
            }
        });
        ansTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansTFActionPerformed(evt);
            }
        });
        jPanel2.add(ansTF);
        ansTF.setBounds(490, 250, 90, 30);

        q1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        q1.setForeground(new java.awt.Color(255, 255, 255));
        q1.setText("Ques Button 1");
        jPanel2.add(q1);
        q1.setBounds(20, 120, 130, 20);

        ques_but1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ques_but1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ques_but1FocusLost(evt);
            }
        });
        ques_but1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ques_but1ActionPerformed(evt);
            }
        });
        jPanel2.add(ques_but1);
        ques_but1.setBounds(180, 120, 40, 26);

        ques_but2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ques_but2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ques_but2FocusLost(evt);
            }
        });
        ques_but2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ques_but2ActionPerformed(evt);
            }
        });
        jPanel2.add(ques_but2);
        ques_but2.setBounds(180, 150, 40, 26);

        ques_but3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ques_but3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ques_but3FocusLost(evt);
            }
        });
        ques_but3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ques_but3ActionPerformed(evt);
            }
        });
        jPanel2.add(ques_but3);
        ques_but3.setBounds(180, 180, 40, 26);

        ques_but4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ques_but4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ques_but4FocusLost(evt);
            }
        });
        ques_but4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ques_but4ActionPerformed(evt);
            }
        });
        jPanel2.add(ques_but4);
        ques_but4.setBounds(180, 210, 40, 26);

        ques_but5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ques_but5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ques_but5FocusLost(evt);
            }
        });
        ques_but5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ques_but5ActionPerformed(evt);
            }
        });
        jPanel2.add(ques_but5);
        ques_but5.setBounds(180, 240, 40, 26);

        ques_but6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ques_but6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ques_but6FocusLost(evt);
            }
        });
        ques_but6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ques_but6ActionPerformed(evt);
            }
        });
        jPanel2.add(ques_but6);
        ques_but6.setBounds(180, 270, 40, 26);

        ques_but7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ques_but7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ques_but7FocusLost(evt);
            }
        });
        ques_but7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ques_but7ActionPerformed(evt);
            }
        });
        jPanel2.add(ques_but7);
        ques_but7.setBounds(180, 300, 40, 26);

        ques_but8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ques_but8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ques_but8FocusLost(evt);
            }
        });
        ques_but8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ques_but8ActionPerformed(evt);
            }
        });
        jPanel2.add(ques_but8);
        ques_but8.setBounds(180, 330, 40, 26);

        jLabel16.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Ans Button 2");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(660, 140, 130, 20);

        ans_but1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ans_but1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ans_but1FocusLost(evt);
            }
        });
        ans_but1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans_but1ActionPerformed(evt);
            }
        });
        jPanel2.add(ans_but1);
        ans_but1.setBounds(800, 110, 40, 26);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.png"))); // NOI18N
        jLabel11.setToolTipText("To Close Game");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
        });
        jPanel2.add(jLabel11);
        jLabel11.setBounds(800, 10, 50, 50);

        jLabel15.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Ques Button 8");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(20, 330, 140, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ques Button 2");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 150, 140, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ques Button 4");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 210, 140, 20);

        q2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        q2.setForeground(new java.awt.Color(255, 255, 255));
        q2.setText("Ques Button 3");
        jPanel2.add(q2);
        q2.setBounds(20, 180, 140, 20);

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Ques Button 7");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(20, 300, 140, 20);

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Ques Button 6");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(20, 270, 140, 20);

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Ques Button 5");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(20, 240, 140, 20);

        insertButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/submit-png.png"))); // NOI18N
        insertButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insertButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                insertButtonMouseEntered(evt);
            }
        });
        jPanel2.add(insertButton);
        insertButton.setBounds(380, 370, 150, 50);

        ans_but2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ans_but2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ans_but2FocusLost(evt);
            }
        });
        ans_but2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans_but2ActionPerformed(evt);
            }
        });
        jPanel2.add(ans_but2);
        ans_but2.setBounds(800, 140, 40, 26);

        ans_but3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ans_but3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ans_but3FocusLost(evt);
            }
        });
        ans_but3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans_but3ActionPerformed(evt);
            }
        });
        jPanel2.add(ans_but3);
        ans_but3.setBounds(800, 170, 40, 26);

        ans_but4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ans_but4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ans_but4FocusLost(evt);
            }
        });
        ans_but4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans_but4ActionPerformed(evt);
            }
        });
        jPanel2.add(ans_but4);
        ans_but4.setBounds(800, 200, 40, 26);

        ans_but5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ans_but5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ans_but5FocusLost(evt);
            }
        });
        ans_but5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans_but5ActionPerformed(evt);
            }
        });
        jPanel2.add(ans_but5);
        ans_but5.setBounds(800, 230, 40, 26);

        ans_but6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ans_but6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ans_but6FocusLost(evt);
            }
        });
        ans_but6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans_but6ActionPerformed(evt);
            }
        });
        jPanel2.add(ans_but6);
        ans_but6.setBounds(800, 260, 40, 26);

        ans_but7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ans_but7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ans_but7FocusLost(evt);
            }
        });
        ans_but7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans_but7ActionPerformed(evt);
            }
        });
        jPanel2.add(ans_but7);
        ans_but7.setBounds(800, 290, 40, 26);

        ans_but8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ans_but8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ans_but8FocusLost(evt);
            }
        });
        ans_but8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans_but8ActionPerformed(evt);
            }
        });
        jPanel2.add(ans_but8);
        ans_but8.setBounds(800, 320, 40, 26);

        jLabel17.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Ans Button 1");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(660, 110, 130, 20);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back.png"))); // NOI18N
        jLabel12.setToolTipText("Click for Back");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
        });
        jPanel2.add(jLabel12);
        jLabel12.setBounds(20, 10, 50, 50);

        jLabel18.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Ans Button 7");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(660, 290, 130, 20);

        jLabel19.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Ans Button 5");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(660, 230, 130, 20);

        jLabel20.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Ans Button 6");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(660, 260, 130, 20);

        jLabel21.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Ans Button 4");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(660, 200, 130, 20);

        jLabel22.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Ans Button 8");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(660, 320, 130, 20);

        jLabel23.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Ans Button 3");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(660, 170, 130, 20);

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Enter # at blank place");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(650, 70, 210, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter # at blank place");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 80, 210, 30);

        usericon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/2pics_small.png"))); // NOI18N
        jPanel2.add(usericon);
        usericon.setBounds(320, 420, 290, 60);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/back.jpg"))); // NOI18N
        jPanel2.add(back);
        back.setBounds(-80, -190, 1020, 760);

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ques Button 3");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 200, 140, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        File clip_loc=new File("src\\music\\exit.wav");
        playMusic(clip_loc);
        int input = JOptionPane.showConfirmDialog(null,
            "Do you want to proceed?", "Select an Option...",JOptionPane.YES_NO_OPTION);

        // 0=yes, 1=no
        if(input == 0)
        {
            dispose();
        }
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        // TODO add your handling code here:
        jLabel11.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        // TODO add your handling code here:
        jLabel12.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel12MouseEntered

    private void insertButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertButtonMouseClicked
        // TODO add your handling code here:
        File clip_loc=new File("src\\music\\Point_gain.wav");
        playMusic(clip_loc);
        insert_record(" inserted ");
        
    }//GEN-LAST:event_insertButtonMouseClicked

    private void insertButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertButtonMouseEntered
        // TODO add your handling code here:
        insertButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_insertButtonMouseEntered

    private void snoTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snoTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snoTFActionPerformed

    private void nolTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nolTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nolTFActionPerformed

    private void ansTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ansTFActionPerformed

    private void ques_but1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ques_but1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ques_but1ActionPerformed

    private void ques_but2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ques_but2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ques_but2ActionPerformed

    private void ques_but3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ques_but3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ques_but3ActionPerformed

    private void ques_but4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ques_but4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ques_but4ActionPerformed

    private void ques_but5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ques_but5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ques_but5ActionPerformed

    private void ques_but6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ques_but6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ques_but6ActionPerformed

    private void ques_but7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ques_but7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ques_but7ActionPerformed

    private void ques_but8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ques_but8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ques_but8ActionPerformed

    private void ans_but1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans_but1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ans_but1ActionPerformed

    private void ans_but2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans_but2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ans_but2ActionPerformed

    private void ans_but3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans_but3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ans_but3ActionPerformed

    private void ans_but4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans_but4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ans_but4ActionPerformed

    private void ans_but5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans_but5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ans_but5ActionPerformed

    private void ans_but6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans_but6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ans_but6ActionPerformed

    private void ans_but7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans_but7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ans_but7ActionPerformed

    private void ans_but8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans_but8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ans_but8ActionPerformed

    private void snoTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_snoTFFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_snoTFFocusLost

    private void ansTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ansTFFocusLost
        // TODO add your handling code here:
        String str=ansTF.getText();
        ansTF.setText(str.toUpperCase());
    }//GEN-LAST:event_ansTFFocusLost

    private void ques_but1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ques_but1FocusLost
        // TODO add your handling code here:
        String str=ques_but1.getText();
        ques_but1.setText(str.toUpperCase());
    }//GEN-LAST:event_ques_but1FocusLost

    private void ques_but2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ques_but2FocusLost
        // TODO add your handling code here:
        String str=ques_but2.getText();
        ques_but2.setText(str.toUpperCase());
    }//GEN-LAST:event_ques_but2FocusLost

    private void ques_but3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ques_but3FocusLost
        // TODO add your handling code here:
        String str=ques_but3.getText();
        ques_but3.setText(str.toUpperCase());
    }//GEN-LAST:event_ques_but3FocusLost

    private void ques_but4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ques_but4FocusLost
        // TODO add your handling code here:
        String str=ques_but4.getText();
        ques_but4.setText(str.toUpperCase());
    }//GEN-LAST:event_ques_but4FocusLost

    private void ques_but5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ques_but5FocusLost
        // TODO add your handling code here:
        String str=ques_but5.getText();
        ques_but5.setText(str.toUpperCase());
    }//GEN-LAST:event_ques_but5FocusLost

    private void ques_but6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ques_but6FocusLost
        // TODO add your handling code here:
        String str=ques_but6.getText();
        ques_but6.setText(str.toUpperCase());
    }//GEN-LAST:event_ques_but6FocusLost

    private void ques_but7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ques_but7FocusLost
        // TODO add your handling code here:
        String str=ques_but7.getText();
        ques_but7.setText(str.toUpperCase());
    }//GEN-LAST:event_ques_but7FocusLost

    private void ques_but8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ques_but8FocusLost
        // TODO add your handling code here:
        String str=ques_but8.getText();
        ques_but8.setText(str.toUpperCase());
    }//GEN-LAST:event_ques_but8FocusLost

    private void ans_but1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ans_but1FocusLost
        // TODO add your handling code here:
        String str=ans_but1.getText();
        ans_but1.setText(str.toUpperCase());
    }//GEN-LAST:event_ans_but1FocusLost

    private void ans_but2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ans_but2FocusLost
        // TODO add your handling code here:
        String str=ans_but2.getText();
        ans_but2.setText(str.toUpperCase());
    }//GEN-LAST:event_ans_but2FocusLost

    private void ans_but3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ans_but3FocusLost
        // TODO add your handling code here:
        String str=ans_but3.getText();
        ans_but3.setText(str.toUpperCase());
    }//GEN-LAST:event_ans_but3FocusLost

    private void ans_but4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ans_but4FocusLost
        // TODO add your handling code here:
        String str=ans_but4.getText();
        ans_but4.setText(str.toUpperCase());
    }//GEN-LAST:event_ans_but4FocusLost

    private void ans_but5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ans_but5FocusLost
        // TODO add your handling code here:
        String str=ans_but5.getText();
        ans_but5.setText(str.toUpperCase());
    }//GEN-LAST:event_ans_but5FocusLost

    private void ans_but6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ans_but6FocusLost
        // TODO add your handling code here:
        String str=ans_but6.getText();
        ans_but6.setText(str.toUpperCase());
    }//GEN-LAST:event_ans_but6FocusLost

    private void ans_but7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ans_but7FocusLost
        // TODO add your handling code here:
        String str=ans_but7.getText();
        ans_but7.setText(str.toUpperCase());
    }//GEN-LAST:event_ans_but7FocusLost

    private void ans_but8FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ans_but8FocusLost
        // TODO add your handling code here:
        String str=ans_but8.getText();
        ans_but8.setText(str.toUpperCase());
    }//GEN-LAST:event_ans_but8FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new insert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ansTF;
    private javax.swing.JTextField ans_but1;
    private javax.swing.JTextField ans_but2;
    private javax.swing.JTextField ans_but3;
    private javax.swing.JTextField ans_but4;
    private javax.swing.JTextField ans_but5;
    private javax.swing.JTextField ans_but6;
    private javax.swing.JTextField ans_but7;
    private javax.swing.JTextField ans_but8;
    private javax.swing.JLabel back;
    private javax.swing.JLabel insertButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nolTF;
    private javax.swing.JLabel q1;
    private javax.swing.JLabel q2;
    private javax.swing.JTextField ques_but1;
    private javax.swing.JTextField ques_but2;
    private javax.swing.JTextField ques_but3;
    private javax.swing.JTextField ques_but4;
    private javax.swing.JTextField ques_but5;
    private javax.swing.JTextField ques_but6;
    private javax.swing.JTextField ques_but7;
    private javax.swing.JTextField ques_but8;
    private javax.swing.JTextField snoTF;
    private javax.swing.JLabel usericon;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icons/coin.png")));
    }
    public void playMusic(File clip_loc)
    {
        try
        {
            Clip clip=AudioSystem.getClip();
            AudioInputStream audioInput=AudioSystem.getAudioInputStream(clip_loc);
            
            clip.open(audioInput);
            clip.start();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
        
    public void insert_record(String str)
    {
        java.sql.PreparedStatement pst=null;
        Connection conn =null;
            
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            conn =(Connection) DriverManager.getConnection("jdbc:mysql://localhost/ram?characterEncoding=latin1", "root", "123456");
            String sql="insert into quiz (sno, q_but1,q_but2 ,q_but3,q_but4,q_but5,q_but6,q_but7,q_but8,a_but1,a_but2,a_but3,a_but4,a_but5,a_but6,a_but7,a_but8,no_of_letter,answer) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            pst=conn.prepareStatement(sql);
            pst.setInt(1, Integer.parseInt(snoTF.getText()));
            pst.setString(2,ques_but1.getText());
            pst.setString(3,ques_but2.getText());
            pst.setString(4,ques_but3.getText());
            pst.setString(5,ques_but4.getText());
            pst.setString(6,ques_but5.getText());
            pst.setString(7,ques_but6.getText());
            pst.setString(8,ques_but7.getText());
            pst.setString(9,ques_but8.getText());
            pst.setString(10,ans_but1.getText());
            pst.setString(11,ans_but2.getText());
            pst.setString(12,ans_but3.getText());
            pst.setString(13,ans_but4.getText());
            pst.setString(14,ans_but5.getText());
            pst.setString(15,ans_but6.getText());
            pst.setString(16,ans_but7.getText());
            pst.setString(17,ans_but8.getText());
            pst.setInt(18,Integer.parseInt(nolTF.getText()));
            pst.setString(19,ansTF.getText());

              pst.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Record "+str+" Successfully !");
        } 
        catch (Exception exc) 
        {
            JOptionPane.showMessageDialog(null, "Enter Correct values!");
        }
        finally
        {
            try 
            {
                conn.close();
                pst.close();
                 dispose();
                new home().setVisible(true);
            } 
            catch(SQLException ex) {
            }           
        }
    }
        public void max_sno()
        {
            int maxSno=0;
            try
           {
             NewClass nw=new NewClass();
              Class.forName("com.mysql.jdbc.Driver");
              Connection conn =(Connection) DriverManager.getConnection("jdbc:mysql://localhost/ram?characterEncoding=latin1", "root", "123456");
              String sql="select max(sno) from quiz ;";
              java.sql.PreparedStatement pst=conn.prepareStatement(sql);
              java.sql.ResultSet rs = pst.executeQuery();
              
                while(rs.next())
                { 
                    maxSno=rs.getInt("max(sno)");
                }
                snoTF.setText((maxSno+1)+"");
              
              conn.close();
              pst.close();
              rs.close();
              
           }
           catch (Exception exc) 
            {
                File clip_loc=new File("src\\music\\exit.wav");
                playMusic(clip_loc);
                JOptionPane.showMessageDialog(null, exc);
            }
        }        
}
