/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import com.mysql.jdbc.Connection;
import java.awt.Cursor;
import java.awt.Toolkit;
import java.io.File;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

/**
 *
 * @author Naveen
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public login() {
        initComponents();
        setLocation(250,100);
        setResizable(false);
        setIcon();
        setTitle("2 Pics 1 Word");   
        user_invalid.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        mickey = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        user_invalid = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jpword = new javax.swing.JPasswordField();
        unameTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        mickey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cartoon/2.png"))); // NOI18N
        jPanel2.add(mickey);
        mickey.setBounds(10, 200, 260, 270);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back.png"))); // NOI18N
        jLabel5.setToolTipText("Click for Back");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
        });
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 10, 50, 50);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/admin_png.png"))); // NOI18N
        jLabel10.setToolTipText("Click for Enter as Admin");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
        });
        jPanel2.add(jLabel10);
        jLabel10.setBounds(760, 0, 100, 100);

        user_invalid.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        user_invalid.setForeground(new java.awt.Color(255, 0, 0));
        user_invalid.setText("*Check your user name or password");
        jPanel2.add(user_invalid);
        user_invalid.setBounds(320, 260, 290, 30);

        jCheckBox1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jCheckBox1.setText("View Password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox1);
        jCheckBox1.setBounds(390, 240, 150, 23);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sign-up-button-png-clipart.png"))); // NOI18N
        jLabel6.setToolTipText("Click for Sign-Up");
        jLabel6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel6FocusGained(evt);
            }
        });
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
        });
        jPanel2.add(jLabel6);
        jLabel6.setBounds(340, 410, 200, 70);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/2pics_small.png"))); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(290, 10, 290, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/login_but-1.png"))); // NOI18N
        jLabel7.setToolTipText("Click to login");
        jLabel7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel7FocusGained(evt);
            }
        });
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
        });
        jPanel2.add(jLabel7);
        jLabel7.setBounds(340, 320, 210, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cartoon/1.png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(600, 200, 280, 290);

        jpword.setBackground(new java.awt.Color(255, 255, 255));
        jpword.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        jpword.setForeground(new java.awt.Color(0, 0, 0));
        jpword.setToolTipText("Enter Your Password");
        jpword.setSelectionColor(new java.awt.Color(0, 0, 0));
        jpword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpwordActionPerformed(evt);
            }
        });
        jPanel2.add(jpword);
        jpword.setBounds(450, 190, 170, 30);

        unameTF.setBackground(new java.awt.Color(255, 255, 255));
        unameTF.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        unameTF.setForeground(new java.awt.Color(0, 0, 0));
        unameTF.setToolTipText("Enter Your Name");
        unameTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                unameTFFocusLost(evt);
            }
        });
        unameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameTFActionPerformed(evt);
            }
        });
        jPanel2.add(unameTF);
        unameTF.setBounds(450, 120, 170, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/password.png"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(220, 190, 220, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_1.png"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(210, 120, 221, 50);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/login_back.jpg"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 860, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel7FocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel7FocusGained

    private void jLabel6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel6FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6FocusGained

    private void jpwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpwordActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
       String uname=unameTF.getText();
       char[] pass1=jpword.getPassword();
        String pass="";
        for(char x:pass1)
            pass=pass+x;   
        
        if(uname.matches(".*[0-9].*") || uname.isBlank()|| uname.length()>10)
        {
            File clip_loc=new File("src\\music\\exit.wav");
            playMusic(clip_loc);
            JOptionPane.showMessageDialog(null,"Enter Correct Name");
            user_invalid.setVisible(true);
            unameTF.setText(null);
        }
        else
        if(pass1.length>10 ||pass1.equals(' ')||pass1.length<=0)
        {
            File clip_loc=new File("src\\music\\exit.wav");
            playMusic(clip_loc);
            JOptionPane.showMessageDialog(null,"Enter Correct Password");
            user_invalid.setVisible(true);
            jpword.setText(null);
        }
       
        else
        { 
           try
           {
             NewClass nw=new NewClass();
              Class.forName("com.mysql.jdbc.Driver");
              Connection conn =(Connection) DriverManager.getConnection("jdbc:mysql://localhost/ram?characterEncoding=latin1", "root", "123456");
              String sql="select * from user where user_name=? and password=?;";
              java.sql.PreparedStatement pst=conn.prepareStatement(sql);
              pst.setString(1, unameTF.getText());
              pst.setString(2, pass);
              java.sql.ResultSet rs = pst.executeQuery();
           
            if(rs.next())
            {
                nw.uname=""+unameTF.getText();
                File clip_loc=new File("src\\music\\submit.wav");
                playMusic(clip_loc);
                JOptionPane.showMessageDialog(null, "Welcome, "+unameTF.getText().toUpperCase());
                dispose();
                new quiz().setVisible(true);
            }
            else
            {
                File clip_loc=new File("src\\music\\exit.wav");
                playMusic(clip_loc);
                JOptionPane.showMessageDialog(null, "Invalid User Name or Password");
                user_invalid.setVisible(true);
            }
              conn.close();
              pst.close();
              rs.close();
           }
           catch (Exception exc) 
            {
                File clip_loc=new File("src\\music\\exit.wav");
                playMusic(clip_loc);
                JOptionPane.showMessageDialog(null, exc);
            }        
        }
       
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
        jLabel7.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        File clip_loc=new File("src\\music\\ques_but.wav");
        playMusic(clip_loc);
        if(jCheckBox1.isSelected())
            jpword.setEchoChar((char)0);
        else
            jpword.setEchoChar('*');
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        File clip_loc=new File("src\\music\\Point_gain.wav");
        playMusic(clip_loc);
        dispose();
        new sign_up().setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        // TODO add your handling code here:
        jLabel10.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
        jLabel6.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        // TODO add your handling code here:
         jLabel5.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        File clip_loc=new File("src\\music\\ques_but.wav");
        playMusic(clip_loc);
        dispose();
        new home().setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void unameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameTFActionPerformed

    private void unameTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_unameTFFocusLost
        // TODO add your handling code here:
        String name=unameTF.getText().toUpperCase();
        unameTF.setText(name);
    }//GEN-LAST:event_unameTFFocusLost

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here
        char[] pass1=jpword.getPassword();
        String pass="";
        for(char x:pass1)
            pass=pass+x;   
        File clip_loc=new File("src\\music\\ques_but.wav");
        playMusic(clip_loc);
        
        if("ADMIN".equals(unameTF.getText()) && "admin".equals(pass))
        {
            JOptionPane.showMessageDialog(rootPane, "You login as Admin !");
            new insert().setVisible(true);
            dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Enter correct Admin name and Password");
        }
            
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jpword;
    private javax.swing.JLabel mickey;
    private javax.swing.JTextField unameTF;
    private javax.swing.JLabel user_invalid;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icons/coin.png")));
    }
    public void playMusic(File clip_loc)
    {
        try
        {
            Clip clip=AudioSystem.getClip();
            AudioInputStream audioInput=AudioSystem.getAudioInputStream(clip_loc);
            
            clip.open(audioInput);
            clip.start();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
}