/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;
import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Toolkit;
import java.io.File;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import java.sql.SQLException;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
/**
 *
 * @author Naveen
 */

public class quiz extends javax.swing.JFrame 
{

    public int quiz_no=0,ans_no=1,totalques;
    public static boolean ansVis1=false,ansVis2=false,ansVis3=false,ansVis4=false,ansVis5=false,ansVis6=false,ansVis7=false,ansVis8=false;
    public static boolean quesVis1=false,quesVis2=false,quesVis3=false,quesVis4=false,quesVis5=false,quesVis6=false,quesVis7=false,quesVis8=false;
    public String ans;
    public static boolean User_ans=true;
    NewClass nc=new NewClass();
    String name=nc.uname;
    public static int imgInc=1,score=0;
    public int no_of_letter,level=1,skipClicked=0; 
    
    
    public quiz() 
    {
        initComponents();
        setLocation(250,100);
        setResizable(false);
        setIcon();
        totalques=max_sno();
        setTitle("2 Pics 1 Word");
        all_button_visible_false();
        get_quiz();
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        submit = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        but_8 = new javax.swing.JButton();
        but_7 = new javax.swing.JButton();
        but_6 = new javax.swing.JButton();
        but_5 = new javax.swing.JButton();
        but_4 = new javax.swing.JButton();
        but_3 = new javax.swing.JButton();
        but_2 = new javax.swing.JButton();
        but_1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        ans_but_1 = new javax.swing.JButton();
        ans_but_2 = new javax.swing.JButton();
        ans_but_3 = new javax.swing.JButton();
        ans_but_4 = new javax.swing.JButton();
        ans_but_5 = new javax.swing.JButton();
        ans_but_6 = new javax.swing.JButton();
        ans_but_7 = new javax.swing.JButton();
        ans_but_8 = new javax.swing.JButton();
        picture1 = new javax.swing.JLabel();
        border1 = new javax.swing.JLabel();
        picture2 = new javax.swing.JLabel();
        border = new javax.swing.JLabel();
        points = new javax.swing.JLabel();
        lEVEL_NO = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/submit-png.png"))); // NOI18N
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                submitMouseEntered(evt);
            }
        });
        jPanel2.add(submit);
        submit.setBounds(370, 420, 160, 50);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/level.png"))); // NOI18N
        jLabel13.setToolTipText("Your Level");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(330, 10, 140, 40);

        but_8.setFont(new java.awt.Font("Gadugi", 1, 20)); // NOI18N
        but_8.setText("H");
        but_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                but_8MouseClicked(evt);
            }
        });
        but_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_8ActionPerformed(evt);
            }
        });
        jPanel2.add(but_8);
        but_8.setBounds(220, 360, 50, 40);

        but_7.setFont(new java.awt.Font("Gadugi", 1, 20)); // NOI18N
        but_7.setText("G");
        but_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_7ActionPerformed(evt);
            }
        });
        jPanel2.add(but_7);
        but_7.setBounds(640, 360, 50, 40);

        but_6.setFont(new java.awt.Font("Gadugi", 1, 20)); // NOI18N
        but_6.setText("F");
        but_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_6ActionPerformed(evt);
            }
        });
        jPanel2.add(but_6);
        but_6.setBounds(280, 360, 50, 40);

        but_5.setFont(new java.awt.Font("Gadugi", 1, 20)); // NOI18N
        but_5.setText("E");
        but_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_5ActionPerformed(evt);
            }
        });
        jPanel2.add(but_5);
        but_5.setBounds(580, 360, 50, 40);

        but_4.setFont(new java.awt.Font("Gadugi", 1, 20)); // NOI18N
        but_4.setText("D");
        but_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_4ActionPerformed(evt);
            }
        });
        jPanel2.add(but_4);
        but_4.setBounds(340, 360, 50, 40);

        but_3.setFont(new java.awt.Font("Gadugi", 1, 20)); // NOI18N
        but_3.setText("C");
        but_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_3ActionPerformed(evt);
            }
        });
        jPanel2.add(but_3);
        but_3.setBounds(520, 360, 50, 40);

        but_2.setFont(new java.awt.Font("Gadugi", 1, 20)); // NOI18N
        but_2.setText("B");
        but_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_2ActionPerformed(evt);
            }
        });
        jPanel2.add(but_2);
        but_2.setBounds(400, 360, 50, 40);

        but_1.setFont(new java.awt.Font("Gadugi", 1, 20)); // NOI18N
        but_1.setText("A");
        but_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                but_1ActionPerformed(evt);
            }
        });
        jPanel2.add(but_1);
        but_1.setBounds(460, 360, 50, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/skip.png"))); // NOI18N
        jLabel8.setToolTipText("Hint: For Image 1");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
        });
        jPanel2.add(jLabel8);
        jLabel8.setBounds(0, 390, 100, 80);

        ans_but_1.setFont(new java.awt.Font("Dialog", 1, 19)); // NOI18N
        ans_but_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans_but_1ActionPerformed(evt);
            }
        });
        jPanel2.add(ans_but_1);
        ans_but_1.setBounds(250, 290, 50, 40);

        ans_but_2.setFont(new java.awt.Font("Dialog", 1, 19)); // NOI18N
        ans_but_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans_but_2ActionPerformed(evt);
            }
        });
        jPanel2.add(ans_but_2);
        ans_but_2.setBounds(300, 290, 50, 40);

        ans_but_3.setFont(new java.awt.Font("Dialog", 1, 19)); // NOI18N
        ans_but_3.setToolTipText("");
        ans_but_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans_but_3ActionPerformed(evt);
            }
        });
        jPanel2.add(ans_but_3);
        ans_but_3.setBounds(350, 290, 50, 40);

        ans_but_4.setFont(new java.awt.Font("Dialog", 1, 19)); // NOI18N
        ans_but_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans_but_4ActionPerformed(evt);
            }
        });
        jPanel2.add(ans_but_4);
        ans_but_4.setBounds(400, 290, 50, 40);

        ans_but_5.setFont(new java.awt.Font("Dialog", 1, 19)); // NOI18N
        ans_but_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans_but_5ActionPerformed(evt);
            }
        });
        jPanel2.add(ans_but_5);
        ans_but_5.setBounds(450, 290, 50, 40);

        ans_but_6.setFont(new java.awt.Font("Dialog", 1, 19)); // NOI18N
        ans_but_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans_but_6ActionPerformed(evt);
            }
        });
        jPanel2.add(ans_but_6);
        ans_but_6.setBounds(500, 290, 50, 40);

        ans_but_7.setFont(new java.awt.Font("Dialog", 1, 19)); // NOI18N
        ans_but_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans_but_7ActionPerformed(evt);
            }
        });
        jPanel2.add(ans_but_7);
        ans_but_7.setBounds(550, 290, 50, 40);

        ans_but_8.setFont(new java.awt.Font("Dialog", 1, 19)); // NOI18N
        ans_but_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans_but_8ActionPerformed(evt);
            }
        });
        jPanel2.add(ans_but_8);
        ans_but_8.setBounds(600, 290, 50, 40);

        picture1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics_1/1.jpg"))); // NOI18N
        jPanel2.add(picture1);
        picture1.setBounds(180, 70, 180, 180);

        border1.setForeground(new java.awt.Color(51, 51, 51));
        border1.setToolTipText("Answer Area");
        border1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true));
        jPanel2.add(border1);
        border1.setBounds(240, 280, 420, 60);

        picture2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics_2/1.jpg"))); // NOI18N
        jPanel2.add(picture2);
        picture2.setBounds(510, 70, 180, 180);

        border.setToolTipText("Answer Area");
        border.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true));
        jPanel2.add(border);
        border.setBounds(170, 60, 530, 200);

        points.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        points.setForeground(new java.awt.Color(255, 255, 255));
        points.setText("0");
        points.setToolTipText("Your Points");
        jPanel2.add(points);
        points.setBounds(770, 0, 90, 70);

        lEVEL_NO.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        lEVEL_NO.setForeground(new java.awt.Color(255, 255, 255));
        lEVEL_NO.setText("1");
        lEVEL_NO.setToolTipText("Your Level");
        jPanel2.add(lEVEL_NO);
        lEVEL_NO.setBounds(480, 0, 90, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Dollar-Coin.png"))); // NOI18N
        jLabel7.setToolTipText("Your Points");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(720, 10, 60, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/addition-icon (1).png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(390, 110, 90, 100);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.png"))); // NOI18N
        jLabel3.setToolTipText("To Close Game");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
        });
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 10, 50, 50);

        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/main_back.jpg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });
        jPanel2.add(jLabel1);
        jLabel1.setBounds(-10, 0, 870, 490);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void but_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_1ActionPerformed
        // TODO add your handling code here
        quesVis1=false;
       ques_button_call(but_1);
    }//GEN-LAST:event_but_1ActionPerformed

    private void but_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_2ActionPerformed
        // TODO add your handling code here:
        quesVis2=false;
        ques_button_call(but_2);
    }//GEN-LAST:event_but_2ActionPerformed

    private void ans_but_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans_but_1ActionPerformed
        // TODO add your handling code here
        ansVis1=false;
        ans_but_click(ans_but_1);        
    }//GEN-LAST:event_ans_but_1ActionPerformed

    private void ans_but_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans_but_2ActionPerformed
        // TODO add your handling code here:
        ansVis2=false;
        ans_but_click(ans_but_2);   
    }//GEN-LAST:event_ans_but_2ActionPerformed

    private void ans_but_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans_but_3ActionPerformed
        // TODO add your handling code here:
       ansVis3=false;
       ans_but_click(ans_but_3);   
    }//GEN-LAST:event_ans_but_3ActionPerformed

    private void ans_but_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans_but_4ActionPerformed
        // TODO add your handling code here:
        ansVis4=false;
        ans_but_click(ans_but_4);   
    }//GEN-LAST:event_ans_but_4ActionPerformed

    private void ans_but_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans_but_5ActionPerformed
        // TODO add your handling code here:
        ansVis5=false;
        ans_but_click(ans_but_5);  
    }//GEN-LAST:event_ans_but_5ActionPerformed

    private void ans_but_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans_but_6ActionPerformed
        // TODO add your handling code here:
        ansVis6=false;
        ans_but_click(ans_but_6);          
    }//GEN-LAST:event_ans_but_6ActionPerformed

    private void ans_but_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans_but_7ActionPerformed
        // TODO add your handling code here:
        ansVis7=false;
        ans_but_click(ans_but_7);         
    }//GEN-LAST:event_ans_but_7ActionPerformed

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        jLabel3.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        // TODO add your handling code here:
        jLabel8.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:        
        updatePoint(score);
        File clip_loc=new File("src\\music\\exit.wav");
        playMusic(clip_loc);
      int input = JOptionPane.showConfirmDialog(null, 
                "Do you want to proceed?", "Select an Option...",JOptionPane.YES_NO_OPTION);

	// 0=yes, 1=no
      if(input == 0) 
      {
          dispose();
          new score().setVisible(true);
      }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void submitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseEntered
        // TODO add your handling code here:
        submit.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_submitMouseEntered

    private void but_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_3ActionPerformed
        // TODO add your handling code here:
        quesVis3=false;
        ques_button_call(but_3);
    }//GEN-LAST:event_but_3ActionPerformed

    private void but_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_4ActionPerformed
        // TODO add your handling code here:
        quesVis4=false;
        ques_button_call(but_4);
        
    }//GEN-LAST:event_but_4ActionPerformed

    private void but_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_5ActionPerformed
        // TODO add your handling code here:
        quesVis5=false;
        ques_button_call(but_5);
    }//GEN-LAST:event_but_5ActionPerformed

    private void but_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_6ActionPerformed
        // TODO add your handling code here:
        quesVis6=false;
        ques_button_call(but_6);
    }//GEN-LAST:event_but_6ActionPerformed

    private void but_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_7ActionPerformed
       quesVis7=false;
        ques_button_call(but_7);
    }//GEN-LAST:event_but_7ActionPerformed

    private void submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMouseClicked
        if(quiz_no<totalques)
        {
            User_ans=checkAnswer();
            System.out.println(ans); 
            if(User_ans==true)
            {
                File clip_loc=new File("src\\music\\Point_gain.wav");
                playMusic(clip_loc);
                imgInc++;
                picture1.setIcon(new ImageIcon(getClass().getResource("/Pics_1/"+imgInc+".jpg")));
                picture2.setIcon(new ImageIcon(getClass().getResource("/Pics_2/"+imgInc+".jpg")));
                all_button_visible_false();
                get_quiz();
                score=score+10;
                level++;
                points.setText(score+"");
                lEVEL_NO.setText(level+"");
            }
            else
            {
                File clip_loc=new File("src\\music\\exit.wav");
                playMusic(clip_loc);
                JOptionPane.showMessageDialog(rootPane, "Wrong Answer");
            }
        }
        else
        {
            User_ans=checkAnswer();
            updatePoint(score);
            if(User_ans==true)
            {
                File clip_loc=new File("src\\music\\Point_gain.wav");
                playMusic(clip_loc);
                JOptionPane.showMessageDialog(null, "You Finished the Game");
                dispose();
                new score().setVisible(true);
            }
            else
            {
                File clip_loc=new File("src\\music\\exit.wav");
                playMusic(clip_loc);
                JOptionPane.showMessageDialog(rootPane, "Wrong Answer");
                dispose();
                new score().setVisible(true);
            }
            
        }
        
            
    }//GEN-LAST:event_submitMouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jLabel1MouseEntered

    private void ans_but_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans_but_8ActionPerformed
        // TODO add your handling code here:
        ansVis8=false;
        ans_but_click(ans_but_8); 
    }//GEN-LAST:event_ans_but_8ActionPerformed

    private void but_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but_8ActionPerformed
        // TODO add your handling code here:
        quesVis8=false;
        ques_button_call(but_8);
        
    }//GEN-LAST:event_but_8ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        if(quiz_no==totalques)
        {
            File clip_loc=new File("src\\music\\Skip.wav");
            playMusic(clip_loc);
            JOptionPane.showMessageDialog(rootPane, "You can't Skip Level Now");
        }
        else
        if(skipClicked==2)
        {
            JOptionPane.showMessageDialog(rootPane, "You can't Skip more than 2 Level");
        }
        else
        {
            int input = JOptionPane.showConfirmDialog(null, 
                    "Do you want to Skip the Level?", "10 Points will be deducted from your score...",JOptionPane.YES_NO_OPTION);
            // 0=yes, 1=no
          if(input == 0) 
          {
              File clip_loc=new File("src\\music\\Point_gain.wav");
                playMusic(clip_loc);
              skipClicked++;
            imgInc++;
            picture1.setIcon(new ImageIcon(getClass().getResource("/Pics_1/"+imgInc+".jpg")));
            picture2.setIcon(new ImageIcon(getClass().getResource("/Pics_2/"+imgInc+".jpg")));
            all_button_visible_false();
            get_quiz();
            skipAnswer();
            score=score-10;
            level++;
            System.out.print(level);
            points.setText(score+"");
            lEVEL_NO.setText(level+"");
          }
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void but_8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but_8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_but_8MouseClicked

    /*
     @param args the command line arguments
     */
    
    public void get_quiz()
    {
        java.sql.PreparedStatement pst=null;
        Connection conn =null;
        java.sql.ResultSet rs = null;
        if(quiz_no<totalques)
        {quiz_no++;
        }
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            conn =(Connection) DriverManager.getConnection("jdbc:mysql://localhost/ram?characterEncoding=latin1", "root", "123456");
            String sql="select * from quiz where sno="+quiz_no+";";
            pst=conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next())
            {   
                no_of_letter=rs.getInt("no_of_letter");
                System.out.println(no_of_letter);
                
                    if(no_of_letter<1)
                    {
                        but_1.setVisible(false);
                    }
                    else
                    {
                        but_1.setVisible(true);
                        quesVis1=true;
                    }
                    if(no_of_letter<2)
                    {
                        but_2.setVisible(false);
                    }
                    else
                    {
                        but_2.setVisible(true);
                        quesVis2=true;
                    }
                    if(no_of_letter<3)
                    {
                        but_3.setVisible(false);
                    }
                    else
                    {
                        but_3.setVisible(true);
                        quesVis3=true;
                    }
                    if(no_of_letter<4)
                    {
                        but_4.setVisible(false);
                    }
                    else
                    {
                        but_4.setVisible(true);
                        quesVis4=true;
                    }
                    if(no_of_letter<5)
                    {
                        but_5.setVisible(false);
                    }
                    else
                    {
                        but_5.setVisible(true);
                        quesVis5=true;
                    }
                    if(no_of_letter<6)
                    {
                        but_6.setVisible(false);
                    }
                    else
                    {
                        but_6.setVisible(true);
                        quesVis6=true;
                    }
                    if(no_of_letter<7)
                    {
                        but_7.setVisible(false);
                    }
                    else
                    {
                        but_7.setVisible(true);
                        quesVis7=true;
                    }
                    if(no_of_letter<8)
                    {
                        but_8.setVisible(false);
                    }
                    else
                    {
                        but_8.setVisible(true);
                        quesVis8=true;
                    }
                    but_1.setText(rs.getString("q_but1").toUpperCase().trim());
                    but_2.setText(rs.getString("q_but2").toUpperCase().trim());
                    but_3.setText(rs.getString("q_but3").toUpperCase().trim());
                    but_4.setText(rs.getString("q_but4").toUpperCase().trim());
                    but_5.setText(rs.getString("q_but5").toUpperCase().trim());
                    but_6.setText(rs.getString("q_but6").toUpperCase().trim());
                    but_7.setText(rs.getString("q_but7").toUpperCase().trim());
                    but_8.setText(rs.getString("q_but8").toUpperCase().trim());
                    
                }
            }
            catch (Exception exc) 
            {
                JOptionPane.showMessageDialog(null, exc);
            }
            finally
            {
                try 
                {
                    conn.close();
                    pst.close();
                    rs.close();  
                } 
                catch(SQLException ex) {
                }           
            }
    }
    public boolean skipAnswer()
    {
            java.sql.PreparedStatement pst=null;
            Connection conn =null;
            java.sql.ResultSet rs = null;
            try
            {
                Class.forName("com.mysql.jdbc.Driver");
                conn =(Connection) DriverManager.getConnection("jdbc:mysql://localhost/ram?characterEncoding=latin1", "root", "123456");
                String sql="select * from quiz where sno="+ans_no+";";
                pst=conn.prepareStatement(sql);
                rs = pst.executeQuery();
                while(rs.next())
                { 
                    ans=rs.getString("answer").toUpperCase().trim();
                }
            } 
            catch (Exception exc) 
            {
                JOptionPane.showMessageDialog(null, exc);
            }
            finally
            {
                try 
                {
                    conn.close();
                    pst.close();
                    rs.close();  
                } 
                catch(SQLException ex) {
                }           
            }
            String str="";
            if(ans_but_1.getText()!=null)
            str=str+ans_but_1.getText();
            if(ans_but_2.getText()!=null)
            str=str+ans_but_2.getText();
            if(ans_but_3.getText()!=null)
            str=str+ans_but_3.getText();
            if(ans_but_4.getText()!=null)
            str=str+ans_but_4.getText();
            if(ans_but_5.getText()!=null)
            str=str+ans_but_5.getText();
            if(ans_but_6.getText()!=null)
            str=str+ans_but_6.getText();
            if(ans_but_7.getText()!=null)
            str=str+ans_but_7.getText();
            if(ans_but_8.getText()!=null)
            str=str+ans_but_8.getText();
            System.out.println("str = "+str);
            System.out.println("Actual answer= "+ans);
            ans_no++;
            return true;
    }

    
    public void updatePoint(int point)
    {
            java.sql.PreparedStatement pst=null;
            Connection conn =null;
            try
            {
                Class.forName("com.mysql.jdbc.Driver");
                conn =(Connection) DriverManager.getConnection("jdbc:mysql://localhost/ram?characterEncoding=latin1", "root", "123456");
                String sql="update user set score="+point+" where user_name=\""+name+"\";";
                pst=conn.prepareStatement(sql);
                pst.execute();
            } 
            catch (Exception exc) 
            {
                JOptionPane.showMessageDialog(null, exc);
            }
            finally
            {
                try 
                {
                    conn.close();
                    pst.close();
                } 
                catch(SQLException ex) {
                }           
            }
    }
    
    public boolean checkAnswer()
    {
        boolean res=false;
            java.sql.PreparedStatement pst=null;
            Connection conn =null;
            java.sql.ResultSet rs = null;
            
            
            try
            {
                Class.forName("com.mysql.jdbc.Driver");
                conn =(Connection) DriverManager.getConnection("jdbc:mysql://localhost/ram?characterEncoding=latin1", "root", "123456");
                String sql="select * from quiz where sno="+ans_no+";";
                pst=conn.prepareStatement(sql);
                rs = pst.executeQuery();
                while(rs.next())
                { 
                    ans=rs.getString("answer").toUpperCase().trim();
                }
            } 
            catch (Exception exc) 
            {
                JOptionPane.showMessageDialog(null, exc);
            }
            finally
            {
                try 
                {
                    conn.close();
                    pst.close();
                    rs.close();  
                } 
                catch(SQLException ex) {
                }           
            }
            String str="";
            if(ans_but_1.getText()!=null)
            str=str+ans_but_1.getText();
            if(ans_but_2.getText()!=null)
            str=str+ans_but_2.getText();
            if(ans_but_3.getText()!=null)
            str=str+ans_but_3.getText();
            if(ans_but_4.getText()!=null)
            str=str+ans_but_4.getText();
            if(ans_but_5.getText()!=null)
            str=str+ans_but_5.getText();
            if(ans_but_6.getText()!=null)
            str=str+ans_but_6.getText();
            if(ans_but_7.getText()!=null)
            str=str+ans_but_7.getText();
            if(ans_but_8.getText()!=null)
            str=str+ans_but_8.getText();
            System.out.println("str = "+str);
            System.out.println("Actual answer= "+ans);
            if(str.equals(ans))
            {
                ans_no++;
                return true;
            }
            else
                res=false;
        
         return res;
    }
    public void all_button_visible_false()
    {
        ans_but_1.setText(null);
        ans_but_2.setText(null);
        ans_but_3.setText(null);
        ans_but_4.setText(null);
        ans_but_5.setText(null);
        ans_but_6.setText(null);
        ans_but_7.setText(null);
        ans_but_8.setText(null);
        but_1.setText(null);
        but_2.setText(null);
        but_3.setText(null);
        but_4.setText(null);
        but_5.setText(null);
        but_6.setText(null);
        but_7.setText(null);
        but_8.setText(null); 
        ans_but_1.setVisible(false);
        ans_but_2.setVisible(false);
        ans_but_3.setVisible(false);
        ans_but_4.setVisible(false);
        ans_but_5.setVisible(false);
        ans_but_6.setVisible(false);
        ans_but_7.setVisible(false);
        ans_but_8.setVisible(false);
        but_1.setVisible(false);
        but_2.setVisible(false);
        but_3.setVisible(false);
        but_4.setVisible(false);
        but_5.setVisible(false);
        but_6.setVisible(false);
        but_7.setVisible(false);
        but_8.setVisible(false);
        ansVis1=false;
        ansVis2=false;
        ansVis3=false;
        ansVis4=false;
        ansVis5=false;
        ansVis6=false;
        ansVis7=false;
        ansVis8=false;
        quesVis1=false;
        quesVis2=false;
        quesVis3=false;
        quesVis4=false;
        quesVis5=false;
        quesVis6=false;
        quesVis7=false;
        quesVis8=false;
    }
    
     public void playMusic(File clip_loc)
    {
        try
        {
            Clip clip=AudioSystem.getClip();
            AudioInputStream audioInput=AudioSystem.getAudioInputStream(clip_loc);
            clip.open(audioInput);
            clip.start();
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
      
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quiz().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ans_but_1;
    private javax.swing.JButton ans_but_2;
    private javax.swing.JButton ans_but_3;
    private javax.swing.JButton ans_but_4;
    private javax.swing.JButton ans_but_5;
    private javax.swing.JButton ans_but_6;
    private javax.swing.JButton ans_but_7;
    private javax.swing.JButton ans_but_8;
    private javax.swing.JLabel border;
    private javax.swing.JLabel border1;
    private javax.swing.JButton but_1;
    private javax.swing.JButton but_2;
    private javax.swing.JButton but_3;
    private javax.swing.JButton but_4;
    private javax.swing.JButton but_5;
    private javax.swing.JButton but_6;
    private javax.swing.JButton but_7;
    private javax.swing.JButton but_8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lEVEL_NO;
    private javax.swing.JLabel picture1;
    private javax.swing.JLabel picture2;
    private javax.swing.JLabel points;
    private javax.swing.JLabel submit;
    // End of variables declaration//GEN-END:variables
    public void ques_button_call(javax.swing.JButton but )
    {
        File clip_loc=new File("src\\music\\ques_but.wav");
        playMusic(clip_loc);
        if(ansVis1==false)
        {
            but.setVisible(false);
            ans_but_1.setVisible(true);
            ans_but_1.setText(but.getText());
            ansVis1=true;
        } 
        else 
        if(ansVis2==false)
        {
            but.setVisible(false);
            ans_but_2.setVisible(true);
            ans_but_2.setText(but.getText());
            ansVis2=true;
        } 
        else 
        if(ansVis3==false)
        {
            but.setVisible(false);
            ans_but_3.setVisible(true);
            ans_but_3.setText(but.getText());
            ansVis3=true;
        }
        else 
        if(ansVis4==false)
        {
            but.setVisible(false);
            ans_but_4.setVisible(true);
            ans_but_4.setText(but.getText());
            ansVis4=true;
        }
        else 
        if(ansVis5==false)
        {
            but.setVisible(false);
            ans_but_5.setVisible(true);
            ans_but_5.setText(but.getText());
            ansVis5=true;
        }
        else 
        if(ansVis6==false)
        {
            but.setVisible(false);
            ans_but_6.setVisible(true);
            ans_but_6.setText(but.getText());
            ansVis6=true;
        }
        else 
        if(ansVis7==false)
        {
            but.setVisible(false);
            ans_but_7.setVisible(true);
            ans_but_7.setText(but.getText());
            ansVis7=true;
        }
        else 
        if(ansVis8==false)
        {
            but.setVisible(false);
            ans_but_8.setVisible(true);
            ans_but_8.setText(but.getText());
            ansVis8=true;
        }
        java.sql.PreparedStatement pst=null;
        Connection conn =null;
        java.sql.ResultSet rs = null;
        String str1="",str2="",str3="",str4="",str5="",str6="",str7="",str8="";
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            conn =(Connection) DriverManager.getConnection("jdbc:mysql://localhost/ram?characterEncoding=latin1", "root", "123456");
            String sql="select * from quiz where sno="+quiz_no+";";
            pst=conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while(rs.next())
            {   
                str1=rs.getString("a_but1");
                str2=rs.getString("a_but2");
                str3=rs.getString("a_but3");
                str4=rs.getString("a_but4");
                str5=rs.getString("a_but5");
                str6=rs.getString("a_but6");
                str7=rs.getString("a_but7");
                str8=rs.getString("a_but8");
            }   
        }
            catch (Exception exc) 
            {
                JOptionPane.showMessageDialog(null, exc);
            }
            finally
            {
                try 
                {
                    conn.close();
                    pst.close();
                    rs.close();  
                } 
                catch(SQLException ex) {
                }           
            }
        
        if(ansVis1==true && ans_but_1.getText().equals(str1))
            ans_but_1.setBackground(Color.green);
        else
            ans_but_1.setBackground(Color.red);
        
        if(ansVis2==true && ans_but_2.getText().equals(str2) )
            ans_but_2.setBackground(Color.green);
        else
            ans_but_2.setBackground(Color.red);
        
        if(ansVis3==true && ans_but_3.getText().equals(str3))
            ans_but_3.setBackground(Color.green);
        else
            ans_but_3.setBackground(Color.red);
        
        if(ansVis4==true && ans_but_4.getText().equals(str4))
            ans_but_4.setBackground(Color.green);
        else
            ans_but_4.setBackground(Color.red);
        
        if(ansVis5==true && ans_but_5.getText().equals(str5))
            ans_but_5.setBackground(Color.green);
        else
            ans_but_5.setBackground(Color.red);
        
        if(ansVis6==true && ans_but_6.getText().equals(str6))
            ans_but_6.setBackground(Color.green);
        else
            ans_but_6.setBackground(Color.red);
        
        if(ansVis7==true && ans_but_7.getText().equals(str7))
            ans_but_7.setBackground(Color.green);
        else
            ans_but_7.setBackground(Color.red);
        
        if(ansVis8==true && ans_but_8.getText().equals(str8))
            ans_but_8.setBackground(Color.green);
        else
            ans_but_8.setBackground(Color.red);
    }
    
    public void ans_but_click(javax.swing.JButton but)
    {
        File clip_loc=new File("src\\music\\ans_but.wav");
        playMusic(clip_loc);
        if(quesVis1==false && 1<=no_of_letter)
        {
            but_1.setText(but.getText());
            but_1.setVisible(true);
            but.setVisible(false);
            but.setText(null);
            but.setBackground(null);            
            quesVis1=true;
        } 
        else 
        if(quesVis2==false && 2<=no_of_letter)
        {
            but_2.setText(but.getText());
            but_2.setVisible(true);
            but.setVisible(false);
            but.setText(null);
            but.setBackground(null); 
            quesVis2=true;
        } 
        else
        if(quesVis3==false && 3<=no_of_letter)
        {
            but_3.setText(but.getText());
            but_3.setVisible(true);
            but.setVisible(false);
            but.setText(null);
            but.setBackground(null); 
            quesVis3=true;
        } 
        else
        if(quesVis4==false && 4<=no_of_letter)
        {
            but_4.setText(but.getText());
            but_4.setVisible(true);
            but.setVisible(false);
            but.setText(null);
            but.setBackground(null); 
            quesVis4=true;
        } 
        else
        if(quesVis5==false  && 5<=no_of_letter)
        {
            but_5.setText(but.getText());
            but_5.setVisible(true);
            but.setVisible(false);
            but.setText(null);
            but.setBackground(null); 
            quesVis5=true;
        } 
        else
        if(quesVis6==false  && 6<=no_of_letter)
        {
            but_6.setText(but.getText());
            but_6.setVisible(true);
            but.setVisible(false);
            but.setText(null);
            but.setBackground(null); 
            quesVis6=true;
        } 
        else
        if(quesVis7==false  && 7<=no_of_letter)
        {
            but_7.setText(but.getText());
            but_7.setVisible(true);
            but.setVisible(false);
            but.setText(null);
            but.setBackground(null); 
            quesVis7=true;
        } 
        else
        if(quesVis8==false&& 8<=no_of_letter)
        {
            but_8.setText(but.getText());
            but_8.setVisible(true);
            but.setVisible(false);
            but.setText(null);
            but.setBackground(null); 
            quesVis8=true;
        }
    }
    public int max_sno()
        {
            int quesNo=0;            
            try
           {
             NewClass nw=new NewClass();
              Class.forName("com.mysql.jdbc.Driver");
              Connection conn =(Connection) DriverManager.getConnection("jdbc:mysql://localhost/ram?characterEncoding=latin1", "root", "123456");
              String sql="select max(sno) from quiz ;";
              java.sql.PreparedStatement pst=conn.prepareStatement(sql);
              java.sql.ResultSet rs = pst.executeQuery();
              
                while(rs.next())
                { 
                    quesNo=rs.getInt("max(sno)");
                }           
              conn.close();
              pst.close();
              rs.close();
              
           }
           catch (Exception exc) 
            {
                File clip_loc=new File("src\\music\\exit.wav");
                playMusic(clip_loc);
                JOptionPane.showMessageDialog(null, exc);
            }
            return quesNo;
        }
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icons/coin.png")));
    }
}